# Generated by Django 4.2.5 on 2023-09-24 19:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name='имя')),
                ('last_name', models.CharField(max_length=50, verbose_name='фамилия')),
                ('bio', models.TextField(blank=True, max_length=500, null=True, verbose_name='о себе')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='дата рождения')),
                ('country', django_countries.fields.CountryField(blank=True, max_length=2, null=True)),
                ('private', models.BooleanField(default=False, verbose_name='приватность')),
                ('gender', models.CharField(blank=True, choices=[('Woman', 'Женский'), ('Man', 'Мужской')], default='W', max_length=16, null=True, verbose_name='пол')),
                ('picture', models.ImageField(blank=True, default='uploads/profile_pictures/default.png', upload_to='uploads/profile_pictures')),
                ('slug', models.SlugField(blank=True, null=True, verbose_name='слаг')),
                ('followers', models.ManyToManyField(blank=True, related_name='followers', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='пользователь')),
            ],
            options={
                'verbose_name': 'Профиль',
                'verbose_name_plural': 'Профили',
            },
        ),
    ]
