# Generated by Django 4.2.5 on 2023-09-28 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_profile_subscriptions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='subscriptions',
        ),
    ]
