# Generated by Django 4.2.6 on 2023-12-29 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_profile_birth_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(blank=True, choices=[('Woman', 'Женский'), ('Man', 'Мужской'), ('Not_defined', 'Не указан')], default='Not_defined', max_length=16, null=True, verbose_name='пол'),
        ),
    ]
