# Generated by Django 4.2.5 on 2023-09-25 21:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import taggit.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0002_alter_profile_first_name_alter_profile_gender_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('taggit', '0005_auto_20220424_2025'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='profile/all_photos', verbose_name='фото')),
                ('description', models.CharField(blank=True, max_length=260, null=True, verbose_name='описание')),
                ('date_create', models.DateTimeField(default=django.utils.timezone.now, verbose_name='дата публикации')),
                ('likes', models.ManyToManyField(blank=True, related_name='likes_images', to=settings.AUTH_USER_MODEL)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile_images', to='users.profile', verbose_name='профиль')),
                ('tag', taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='теги')),
            ],
            options={
                'verbose_name': 'Фотки пользователя',
                'verbose_name_plural': 'Фотки пользователей',
            },
        ),
    ]
