# Generated by Django 4.2.5 on 2023-09-30 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_notification_notification_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='profileimage',
            name='count_views',
            field=models.ManyToManyField(blank=True, related_name='count_views', to='core.ip'),
        ),
    ]
