# Generated by Django 4.2.6 on 2023-10-23 21:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_notification_notification_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profileimage',
            options={'ordering': ('-date_create',), 'verbose_name': 'Фотки пользователя', 'verbose_name_plural': 'Фотки пользователей'},
        ),
    ]
