# Generated by Django 4.2.5 on 2023-09-29 11:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatmodel',
            name='receiver',
        ),
        migrations.RemoveField(
            model_name='chatmodel',
            name='user',
        ),
        migrations.AddField(
            model_name='chatmodel',
            name='users',
            field=models.ManyToManyField(related_name='+', to=settings.AUTH_USER_MODEL),
        ),
    ]
