# Generated by Django 4.2.5 on 2023-09-30 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_remove_chatmodel_users_chatmodel_receiver_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chatmodel',
            old_name='receiver',
            new_name='from_user',
        ),
        migrations.RenameField(
            model_name='chatmodel',
            old_name='user',
            new_name='to_user',
        ),
    ]
