# Generated by Django 4.2.5 on 2023-10-01 14:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_rename_receiver_chatmodel_from_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messagemodel',
            name='chat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='all_messages', to='chat.chatmodel', verbose_name='чат'),
        ),
    ]
