# Generated by Django 4.2.5 on 2023-10-01 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_alter_messagemodel_chat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messagemodel',
            name='body',
            field=models.CharField(blank=True, max_length=1000, verbose_name='текст'),
        ),
    ]
