# Generated by Django 4.2.5 on 2023-10-03 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_alter_messagemodel_body'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='messagemodel',
            name='image',
        ),
    ]
